// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uufqzrpwvxynskmcurgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1ZnF6cnB3dnh5bnNrbWN1cmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTE4MDUsImV4cCI6MjA2NTg2NzgwNX0.0yy4N7q4CL691eAyiWU04OkW7LjAcZI9CGTnxgy1Q1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);